@startuml

abstract class Asset {
-String name
-int price
}

abstract class TangibleAsset extends Asset implements Thing{
-String color
+String name
+int price
}
abstract class IntangibleAsset extends Asset {
+String name
+int price

}
class Computer extends TangibleAsset {
-String makerName
+String name
+int price
+double weight
+String color
}

class Book extends TangibleAsset {
-String isbn
+String name
+int price
+double weight
+String color
}

class Patent extends IntangibleAsset {
+String name
+int price

}
interface Thing {
double getWeight();
void setWeight(double weight);
}


@enduml